"""clerk user id update

Revision ID: df82501283d8
Revises: 7f894d40e419
Create Date: 2026-04-28 21:57:11.406459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "df82501283d8"
down_revision: Union[str, Sequence[str], None] = "7f894d40e419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("clerk_id", sa.String(length=255), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["clerk_id"])
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "first_name")
    op.drop_column("users", "clerk_id")
    # ### end Alembic commands ###
